version: "3.1"

services:
  hex-microservice:
    image:  franklincarrero/hex-microservice
    ports:
      - 8000:8000
    expose:
      - 8000
    environment:
      URL_DB: redis
      REDIS_URL:  redis://redisdb:6379
    links:
      - redisdb

  redisdb:
    image:  redis
    ports:
      - 6379:6379
