version: "3.1"

services:
  hex-microservice:
    build: .
    depends_on:
      - redisdb
    ports:
      - 9200:9200
    env_file: 
      - .env
    links:
      - redisdb
  redisdb:
    image:  redis
    ports:
      - 6379:6379
